# Generated by Django 4.1.3 on 2022-11-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticlePublishTime",
            fields=[
                ("source", models.TextField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("log", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
