# Generated by Django 4.1.3 on 2022-12-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticlepublishtime",
            name="postno",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
